#include "font.h"

static vtclock_font vtclock_font_1 = {
  12,15,6,
  {
    
    "    XXXXXX   \n"
    "  XXX    XXX \n"
    " XX        XX\n"
    " XX        XX\n"
    " XX        XX\n"
    " XX        XX\n"
    " XX        XX\n"
    " XX        XX\n"
    " XX        XX\n"
    " XX        XX\n"
    "  XXX    XXX \n"
    "    XXXXXX   \n"
    ,
    "      XX     \n"
    "   XXXXX     \n"
    "      XX     \n"
    "      XX     \n"
    "      XX     \n"
    "      XX     \n"
    "      XX     \n"
    "      XX     \n"
    "      XX     \n"
    "      XX     \n"
    "      XX     \n"
    "   XXXXXXXX  \n"
    ,
    "    XXXXXX   \n"
    "  XXX    XXX \n"
    " XX        XX\n"
    "           XX\n"
    "         XXX \n"
    "       XXX   \n"
    "     XXX     \n"
    "   XXX       \n"
    "  XX         \n"
    " XX          \n"
    " XX          \n"
    " XXXXXXXXXXXX\n"
    ,
    "    XXXXXX   \n"
    "  XXX    XXX \n"
    " XX        XX\n"
    "           XX\n"
    "         XXX \n"
    "      XXXX   \n"
    "         XXX \n"
    "           XX\n"
    "           XX\n"
    " XX        XX\n"
    "  XXX    XXX \n"
    "    XXXXXX   \n"
    ,
    "        XXX  \n"
    "       XXXX  \n"
    "      XX XX  \n"
    "     XX  XX  \n"
    "    XX   XX  \n"
    "   XX    XX  \n"
    "  XX     XX  \n"
    " XXXXXXXXXXXX\n"
    "         XX  \n"
    "         XX  \n"
    "         XX  \n"
    "         XX  \n"
    ,
    " XXXXXXXXXXXX\n"
    " XX          \n"
    " XX          \n"
    " XX          \n"
    " XXXXXXXXX   \n"
    "         XXX \n"
    "           XX\n"
    "           XX\n"
    "           XX\n"
    " XX        XX\n"
    "  XXX    XXX \n"
    "    XXXXXX   \n"
    ,
    "       XXXXX \n"
    "     XXX     \n"
    "   XXX       \n"
    "  XX         \n"
    " XX          \n"
    " XX XXXXXX   \n"
    " XXXX    XXX \n"
    " XX        XX\n"
    " XX        XX\n"
    " XX        XX\n"
    "  XXX    XXX \n"
    "    XXXXXX   \n"
    ,
    " XXXXXXXXXXXX\n"
    "          XX \n"
    "         XX  \n"
    "        XX   \n"
    "       XX    \n"
    "      XX     \n"
    "     XX      \n"
    "     XX      \n"
    "    XX       \n"
    "    XX       \n"
    "    XX       \n"
    "    XX       \n"
    ,
    "    XXXXXX   \n"
    "  XXX    XXX \n"
    " XX        XX\n"
    " XX        XX\n"
    "  XXX    XXX \n"
    "    XXXXXX   \n"
    "  XXX    XXX \n"
    " XX        XX\n"
    " XX        XX\n"
    " XX        XX\n"
    "  XXX    XXX \n"
    "    XXXXXX   \n"
    ,
    "    XXXXXX   \n"
    "  XXX    XXX \n"
    " XX        XX\n"
    " XX        XX\n"
    " XX        XX\n"
    "  XXX    XXXX\n"
    "    XXXXXX XX\n"
    "           XX\n"
    "          XX \n"
    "        XXX  \n"
    "      XXX    \n"
    "  XXXXX      \n"
  },
  "    \n"
  "    \n"
  " XXX\n"
  " XXX\n"
  "    \n"
  "    \n"
  "    \n"
  "    \n"
  " XXX\n"
  " XXX\n"
  "    \n"
  "    \n"
};
